### ISSUE TITLE
IndexError: invalid index to scalar variable.

### ISSUE THREAD

**Issue by wineone** [jeffgreenca/laughr#6]
hello, i'm having a problem executing the code. the following error appears when I run:

```
Traceback (most recent call last):
  File "laughr.py", line 292, in <module>
    model=localModel)
  File "laughr.py", line 202, in do_mute_laughs
    laughr.remove_laughs(sourceFile, outFile)
  File "laughr.py", line 147, in remove_laughs
    rc.laughs = self.model.predict(rc.build_features())
  File "laughr.py", line 73, in build_features
    self.raw = self.y.T[0][i * chunkLen:(i + 1) * chunkLen]
IndexError: invalid index to scalar variable.
```

I am using the following versions of keras and tensorflow:

```
keras==2.2.4
tensorflow==1.14
```

I think it may be an error in which version of the libraries I am using. thanks for listening.

**Comment by GrND-CNYON** [comment]
I'm actually encountering the same issue. How did you solve it? my keras version is '2.4.3' and my tensorflow version is '2.4.1'
