### ISSUE TITLE
Ability to process multiple files at the same time

### ISSUE THREAD

**Issue by AnkushMalaker** [jeffgreenca/laughr#9]
Is there any way to use this tool on a bunch of files at the same time? 

1. Using a loop to iterate through files and call the utility for each file is redundant as it loads the weights again for each file.
2. Creating a LaughRemover Object and using the remove_laughs method solves issue 1 but it's still inefficient as it feeds a single audio sample to the model at each time step.

A way to process multiple files at the same time via batching and possibly a package might be a great help for data science projects that need to process whole dataests.

**Comment by jeffg-dev** [comment]
PRs welcome

**Comment by AnkushMalaker** [comment]
Added [PR](https://github.com/jeffgreenca/laughr/pull/10). I have only fixed issue 1 mentioned above, I have to work on the second point by implementing the padding. 
While working on this, also had two issues:
1. Because of the dependence on soundfile, which depends on libsndfile, , mp3 files can't be loaded. See [this](https://github.com/libsndfile/libsndfile/issues/258).
2. Why does the laugh_remover function return rc? I have left the return statement in the PR I submitted but I don't see it being used anywhere where the function is called.

**Comment by jeffg-dev** [comment]
> Why does the laugh_remover function return rc? I have left the return statement in the PR I submitted but I don't see it being used anywhere where the function is called.

Probably just leftover. Feel free to put up a PR to remove it.

> Padding

I think let's close this as you've implemented a great first iteration. If you want open a second issue to track (2)
